version: '3.7'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nestjs-devtraining
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres/
    container_name: nestjs-devtraining-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestdb

  pgadmin:
    image: dpage/pgadmin4
    container_name: cursonestjs-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
