version: '3'

services:
  app:
    build: ./Dockerfile
    entrypoint: .docker/entrypoint.sh
    container_name: nestjs-devtraining
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .ddocker/postgres
    container_name: nestjs-devtraining-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest
